### ISSUE TITLE
SickChill stopped and won't start again

### ISSUE THREAD

**Issue by peervdb** [BenjV/SYNO-packages#32]
A few weeks ago I installed the latest package from https://github.com/BenjV/SYNO-packages to fix the issue with the proposed update. This worked perfectly until a few days ago, when the package stopped by itself and won't start up again.
![SickChill package stopped 2021-06-21 201912](https://user-images.githubusercontent.com/86257479/122809263-2a515000-d2ce-11eb-9612-6747709f5b71.png)
![Failed 2021-06-21 202025](https://user-images.githubusercontent.com/86257479/122809278-3210f480-d2ce-11eb-9ba7-29c19f824c04.png)

**Comment by BenjV** [comment]
I had the same problem.
Most likely caused by an update of SickChill self.
I was fed up with this package and changed to Medusa.

I just tried to install SickChill new and it did sart normally.
You can try to do a new manual install of SickChill, this will upgrade to the latest version of SickChill.
Maybe it will start again then.

**Comment by peervdb** [comment]
Thanks! Maybe it's a good time to start with Medusa myself :)

**Comment by Smiggel** [comment]
> I had the same problem.
> Most likely caused by an update of SickChill self.
> I was fed up with this package and changed to Medusa.
> 
> I just tried to install SickChill new and it did start normally.
> You can try to do a new manual install of SickChill, this will upgrade to the latest version of SickChill.
> Maybe it will start again then.

Tried that, but no luck here. Will not start after updating.
